### ISSUE TITLE
IndexError: File for year:2014 not found

### ISSUE THREAD

**Issue by sanket-p** [tjvandal/deepsd#2]
Hey guys.. I am trying to run prism.py and download the dataset to my system but it is showing IndexError : File not found for that specific year.

I am using python 3.5 and converted the codes to make it compatible with python 3
I am getting these errors (i have been trying to fetch data for year 2004)...

Year: 2004
data dir data/prism/ppt/raw
Traceback (most recent call last):
  File "prism.py", line 361, in <module>
    main_prism_tf(config)
  File "prism.py", line 324, in main_prism_tf
    config.get('Paths', 'elevation'), model=model.lower())
  File "prism.py", line 187, in __init__
    super(PrismSuperRes, self).__init__(data_dir, year, elevation_file, var=var)
  File "prism.py", line 155, in __init__
    self.read_data()
  File "prism.py", line 178, in read_data
    self._read_highres()
  File "prism.py", line 169, in _read_highres
    highres_file = self._get_year_file()
  File "prism.py", line 164, in _get_year_file
    raise IndexError("File for year:%i not found" % self.year)
IndexError: File for year:2004 not found

can someone tell me the soultion please...

**Comment by sanket-p** [comment]
that was because of some miss handling of codes while converting to python 3. So I switched to python 2.7 and now its working

**Comment by duguangmeiyu** [comment]
Year: 2014
data dir data/prism/ppt/raw
Traceback (most recent call last):
  File "prism.py", line 361, in <module>
    main_prism_tf(config)
  File "prism.py", line 324, in main_prism_tf
    config.get('Paths', 'elevation'), model=model.lower())
  File "prism.py", line 187, in __init__
    super(PrismSuperRes, self).__init__(data_dir, year, elevation_file, var=var)
  File "prism.py", line 155, in __init__
    self.read_data()
  File "prism.py", line 178, in read_data
    self._read_highres()
  File "prism.py", line 169, in _read_highres
    highres_file = self._get_year_file()
  File "prism.py", line 164, in _get_year_file
    raise IndexError("File for year:%i not found" % self.year)
IndexError: File for year:2014 not found

Hello man, I have faced the same problem just like you, and I used python 2.7 and it still doesn't work, do you know how to make it work,thank you very much.

> that was because of some miss handling of codes while converting to python 3. So I switched to python 2.7 and now its working
