### ISSUE TITLE
IndexError: File for year:2014 not found

### ISSUE THREAD

**Issue by duguangmeiyu** [tjvandal/deepsd#7]
Hello, I have faced the following problem and I used python 2.7 to run this code,can you help me to solve this problem please?Thank you very much.

data dir data/prism/ppt/raw
Traceback (most recent call last):
  File "prism.py", line 361, in <module>
    main_prism_tf(config)
  File "prism.py", line 324, in main_prism_tf
    config.get('Paths', 'elevation'), model=model.lower())
  File "prism.py", line 187, in __init__
    super(PrismSuperRes, self).__init__(data_dir, year, elevation_file, var=var)
  File "prism.py", line 155, in __init__
    self.read_data()
  File "prism.py", line 178, in read_data
    self._read_highres()
  File "prism.py", line 169, in _read_highres
    highres_file = self._get_year_file()
  File "prism.py", line 164, in _get_year_file
    raise IndexError("File for year:%i not found" % self.year)
IndexError: File for year:2014 not found

**Comment by daman1209arora** [comment]
You need to enable internet access on your machine, and download the dataset.

**Comment by Afshinshafei** [comment]
I have the same problem. I am using google colab, and have the same error.

**Comment by XiaochenLiuUnibz** [comment]
So how to solve this problem on colab?
